### ISSUE TITLE
install-driver.sh fails on Kali linux with kernel 6.16.8

### ISSUE THREAD

**Issue by forlayo** [morrownr/8814au#159]
`┌──(kali㉿kali)-[~/8814au]
└─$ sudo ./install-driver.sh
: ---------------------------
: install-driver.sh v20230227
: x86_64 (architecture)
: 2/2 (in-use/total processing units)
: 2018416 (total system memory)
: 6.16.8+kali-amd64 (kernel version)
: gcc (Debian 14.3.0-10) 14.3.0
: dkms-3.2.2
: mokutil not installed
: ---------------------------

Checking for previously installed drivers.
: ---------------------------

Starting installation.
Installing 8814au.conf to /etc/modprobe.d
The dkms installation routines are in use.
Copying source files to /usr/src/rtl8814au-5.8.5.1
Creating symlink /var/lib/dkms/rtl8814au/5.8.5.1/source -> /usr/src/rtl8814au-5.8.5.1
The driver was added to dkms successfully.
: ---------------------------
Sign command: /lib/modules/6.16.8+kali-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
kernelver=6.16.8+kali-amd64 ./dkms-make.sh

Error! Bad return status for module build on kernel: 6.16.8+kali-amd64 (x86_64)
Consult /var/lib/dkms/rtl8814au/5.8.5.1/build/make.log for more information.
An error occurred. dkms build error:  10
Please report this error.
Please copy all screen output and paste it into the problem report.
Run the following before reattempting installation.
$ sudo ./remove-driver.sh
                                                                                                        
┌──(kali㉿kali)-[~/8814au]
└─$ cat /var/lib/dkms/8814au/5.8.5.1/build/make.log
                                                                                                        
┌──(kali㉿kali)-[~/8814au]
└─$ cat /var/lib/dkms/rtl8814au/5.8.5.1/build/make.log
DKMS (dkms-3.2.2) make.log for rtl8814au/5.8.5.1 for kernel 6.16.8+kali-amd64 (x86_64)
Sun Nov  9 04:27:13 PM EST 2025

Building module(s)
# command: kernelver=6.16.8+kali-amd64 ./dkms-make.sh
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.16.8+kali-amd64/build M=/var/lib/dkms/rtl8814au/5.8.5.1/build  modules
make[1]: Entering directory '/usr/src/linux-headers-6.16.8+kali-amd64'
make[2]: Entering directory '/var/lib/dkms/rtl8814au/5.8.5.1/build'
  CC [M]  core/rtw_cmd.o
  CC [M]  core/rtw_security.o
core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.16.8+kali-common/scripts/Makefile.build:292: core/rtw_cmd.o] Error 1
make[4]: *** Waiting for unfinished jobs....
core/rtw_security.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.16.8+kali-common/scripts/Makefile.build:292: core/rtw_security.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.16.8+kali-common/Makefile:2027: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.16.8+kali-common/Makefile:260: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/rtl8814au/5.8.5.1/build'
make[1]: *** [/usr/src/linux-headers-6.16.8+kali-common/Makefile:260: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.16.8+kali-amd64'
make: *** [Makefile:2402: modules] Error 2

# exit code: 2
# elapsed time: 00:00:00
----------------------------------------------------------------
`

**Comment by morrownr** [comment]
Hi @forlayo 

The driver in this repo is working as designed. Please read the README from the top. Work on the driver in this repo stopped with kernel 6.14 as a new driver headed into mainline and is in mainline as of kernel 6.16. Please follow the instructions to remove this driver and then reboot. See if the adapter is working. If it is not working then you can file an issue at the following site:

https://github.com/lwfinger/rtw88

Edit: An alternative is to go to the site Main Menu:

https://github.com/morrownr/USB-WiFi/tree/main

And file an issue there.

**Comment by joseguzman1337** [comment]
Maintainer resolution update for #159: **install-driver.sh fails on Kali linux with kernel 6.16.8**

From your pasted `make.log`, DKMS is building from `/var/lib/dkms/rtl8814au/5.8.5.1/build` and fails with:
`fatal error: drv_types.h: No such file or directory`.

Resolution applied in PR #3 / commit `b1866ce2b857a8dfe2e147e19eb8eca0a842ce18`:

1) **Harden DKMS source staging** so DKMS gets a complete tree (including `include/drv_types.h`) and we fail early with a clear message if staging is incomplete.
- Commit: https://github.com/morrownr/8814au/commit/b1866ce2b857a8dfe2e147e19eb8eca0a842ce18
- Implementation: https://github.com/morrownr/8814au/blob/b1866ce2b857a8dfe2e147e19eb8eca0a842ce18/install-driver.sh#L337

2) **Make the build include path work in both in-tree and DKMS “M=” builds** by explicitly adding both `$(src)/include` and `$(M)/include`.
- Implementation: https://github.com/morrownr/8814au/blob/b1866ce2b857a8dfe2e147e19eb8eca0a842ce18/Makefile#L57

Maintainer verification (Kali GNU/Linux Rolling `VERSION_ID=2025.4`, kernel `6.18.5+kali-amd64`, `dkms-3.2.2`):
- DKMS build: PASS
- DKMS install: PASS (`dkms status` shows `rtl8814au/5.8.5.1, 6.18.5+kali-amd64, x86_64: installed`)
- Module load: PASS (`lsmod` shows `8814au` loaded; `modinfo 8814au` reports filename under `/lib/modules/.../updates/dkms/8814au.ko.xz`)

Please retry on current `main`. If it still fails on your Kali 6.16.8 system, paste:
- `ls -la /var/lib/dkms/rtl8814au/5.8.5.1/source/include/drv_types.h`
- `ls -la /var/lib/dkms/rtl8814au/5.8.5.1/build/include/drv_types.h`
- the full `/var/lib/dkms/rtl8814au/5.8.5.1/build/make.log`
